create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  "userName" text not null default '',
  "userEmail" text not null default '',
  amount text not null default '',
  "fileName" text not null default '',
  "fileType" text not null default '',
  "fileData" text not null default '',
  "fileSize" text not null default '',
  "uploadTime" text not null default '',
  status text not null default 'PENDING',
  "uploadDate" date not null default current_date,
  "approvalTime" text not null default '',
  "approvedBy" text not null default '',
  "adminComment" text not null default '',
  "rejectionTime" text not null default '',
  "rejectionReason" text not null default '',
  "rejectedBy" text not null default '',
  "submittedAt" timestamptz not null default now(),
  source text not null default 'user-side'
);

alter table public.payments enable row level security;

-- Temporary policies for the current unauthenticated prototype.
-- Replace these with authenticated admin/user policies before production use.
drop policy if exists "public can read payments" on public.payments;
drop policy if exists "public can submit payments" on public.payments;
drop policy if exists "public can update payments" on public.payments;

create policy "public can read payments"
  on public.payments for select to anon, authenticated using (true);

create policy "public can submit payments"
  on public.payments for insert to anon, authenticated with check (true);

create policy "public can update payments"
  on public.payments for update to anon, authenticated using (true) with check (true);
